name: Sepa Precios Archiver

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 6 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  archive-prices:
    runs-on: ubicloud-standard-8-arm

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Run archiver script
        env:
          GITHUB_TOKEN: ${{ secrets.ARCHIVE_GITHUB_TOKEN }}
          B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
          B2_BUCKET_KEY_ID: ${{ secrets.B2_BUCKET_KEY_ID }}
          B2_BUCKET_KEY: ${{ secrets.B2_BUCKET_KEY }}
        run: |
          cd sepa-precios-archiver
          bun install --frozen-lockfile
          bun index.ts
